#!/usr/bin/env node
/**
 * tools/offsets/gen_offsets_header.mjs
 *
 * Emit src/memory/offsets_table.inc — the C++ table the DLL compiles in.
 *
 * The generator is the guard rail for docs/OFFSETS.md's "never guess" law:
 *   - every key must exist in map_offsets.mjs KEYMAP (a renamed key is a build error);
 *   - every value must be a hex string and every kind ∈ {rva, offset};
 *   - the version string must be present, because core::Initialize refuses to
 *     trust the table when it cannot tell which client build it describes.
 *
 * Default mode writes the .inc; --check validates and prints a summary only
 * (used by `npm run offsets:header` and by CI where the tree must stay clean).
 *
 * Usage:
 *   node tools/offsets/gen_offsets_header.mjs [--in src/memory/offsets_embedded.json] [--out src/memory/offsets_table.inc]
 *   node tools/offsets/gen_offsets_header.mjs --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { KEYMAP, SCHEMA } from "./map_offsets.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");
const DEFAULT_IN = resolve(ROOT, "src/memory/offsets_embedded.json");
const DEFAULT_OUT = resolve(ROOT, "src/memory/offsets_table.inc");

const HEX = /^0x[0-9A-Fa-f]+$/;
const KINDS = new Set(["rva", "offset"]);

export function validate(embedded) {
  const errors = [];
  if (embedded?.schema !== SCHEMA) {
    errors.push(`schema mismatch: expected ${SCHEMA}, got ${String(embedded?.schema)}`);
  }
  if (!embedded?.roblox_version || !/^version-[0-9a-f]{16}$/.test(embedded.roblox_version)) {
    errors.push(`roblox_version missing or malformed: ${String(embedded?.roblox_version)}`);
  }
  const offsets = embedded?.offsets ?? {};
  const keys = Object.keys(offsets);
  if (keys.length === 0) errors.push("no offsets in table");
  for (const [key, spec] of Object.entries(offsets)) {
    if (!(key in KEYMAP)) errors.push(`key not in KEYMAP (rename the tool, not the data): ${key}`);
    if (!HEX.test(String(spec?.value))) errors.push(`${key}: value is not hex: ${String(spec?.value)}`);
    if (!KINDS.has(spec?.kind)) errors.push(`${key}: kind must be rva|offset, got ${String(spec?.kind)}`);
    if (!spec?.from) errors.push(`${key}: missing provenance (which dumper path it came from)`);
  }
  for (const key of Object.keys(KEYMAP)) {
    if (!(key in offsets)) errors.push(`KEYMAP key absent from table (dump had 0 or lacks it): ${key}`);
  }
  return { errors, count: keys.length };
}

export function emit(embedded) {
  const rows = Object.entries(embedded.offsets)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, spec]) =>
      `    { "${key}", ${spec.value}ull, off::Kind::${spec.kind}, "${spec.from}" },`)
    .join("\n");
  return `// GENERATED by tools/offsets/gen_offsets_header.mjs — do not edit.
// source        : ${embedded.source}
// roblox version: ${embedded.roblox_version}
// dumper        : ${embedded.dumper_version} @ ${embedded.dumped_at}
// keys          : ${Object.keys(embedded.offsets).length} (of ${embedded.total_in_dump} in the dump)
//
// Kind::rva    = image-relative pointer (value is added to the client module base)
// Kind::offset = struct offset from the object named by the key's parent
#pragma once

#define PHETAMINE_ROBLOX_VERSION L"${embedded.roblox_version}"
#define PHETAMINE_OFFSETS_SOURCE "${embedded.source}"
#define PHETAMINE_OFFSETS_DUMPED_AT "${embedded.dumped_at}"

namespace off::table {
    inline constexpr Row kRows[] = {
${rows}
    };
    inline constexpr size_t kCount = sizeof(kRows) / sizeof(kRows[0]);
}
`;
}

function main(argv) {
  const arg = (flag, dflt) => {
    const i = argv.indexOf(flag);
    return i === -1 ? dflt : argv[i + 1];
  };
  const inPath = resolve(arg("--in", DEFAULT_IN));
  const outPath = resolve(arg("--out", DEFAULT_OUT));
  const check = argv.includes("--check");

  let embedded;
  try {
    embedded = JSON.parse(readFileSync(inPath, "utf8"));
  } catch (err) {
    console.error(`cannot read ${relative(ROOT, inPath)}: ${err.message}`);
    return 2;
  }
  const { errors, count } = validate(embedded);
  if (errors.length) {
    console.error(`offsets table INVALID (${errors.length} error(s)):`);
    for (const e of errors) console.error(`  - ${e}`);
    return 1;
  }
  if (check) {
    console.error(`offsets table OK — ${count} keys, ${embedded.roblox_version}`);
    return 0;
  }
  writeFileSync(outPath, emit(embedded));
  console.error(`wrote ${relative(ROOT, outPath)} — ${count} keys, ${embedded.roblox_version}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = main(process.argv.slice(2));
}
